### PR TITLE
GH40: Filter GAC assemblies on full framework only

### LINKED ISSUE #40: The Global Assembly Cache is not supported for net5.0 target
I changed [gitfool/BoardGameGeek.Dungeon](https://github.com/gitfool/BoardGameGeek.Dungeon) to [retarget .NET 5.0](https://github.com/gitfool/BoardGameGeek.Dungeon/commit/40eca7ef8ae20a6b377a489749ca5ad3d522976c) (RC1) and this flushed out an issue with `PocketContainer`, which I use indirectly via [`PocketLogger`](https://github.com/gitfool/BoardGameGeek.Dungeon/blob/master/Application/Application.csproj#L15). I pushed the build to GitHub anyway, to show the [failure](https://github.com/gitfool/BoardGameGeek.Dungeon/runs/1137056472#step:6:249):
```
/__w/BoardGameGeek.Dungeon/BoardGameGeek.Dungeon/.nuget/packages/pocket.typediscovery/0.4.0/contentFiles/cs/netstandard2.0/(Pocket)/Discover.cs(60,35): error CS0618: 'Assembly.GlobalAssemblyCache' is obsolete: 'The Global Assembly Cache is not supported.' [/__w/BoardGameGeek.Dungeon/BoardGameGeek.Dungeon/Application/Application.csproj]
```
Coming from: https://github.com/jonsequitur/PocketContainer/blob/6e5f8d8450a0d15d9d72632ad38f6e085c9013e1/Pocket.Container/Discover.cs#L56-L61
Use of `GlobalAssemblyCache` should probably be removed or wrapped by a conditional `#if` directive.

### PR DESCRIPTION
**Pull request by gitfool**
Fixes #40.

### CODE REVIEW

**Comment by gitfool** [comment]
@jonsequitur please review.

Note: `System.Reflection.GlobalAssemblyCache` throws `System.NotImplementedException` for .NET Core:
```c#
/*
  Returns true if the assembly was loaded from the global assembly cache.
*/
public virtual bool GlobalAssemblyCache { get { throw NotImplemented.ByDesign; } }
```
... so I wrapped it in `#if NETFRAMEWORK`.

Also, I bumped all dependencies, which shouldn't matter since this is a source NuGet package, but it needed some love. 😉

**Review by jonsequitur — APPROVED** [review]

**Comment by jonsequitur** [comment]
Thanks, @gitfool!

**Comment by gitfool** [comment]
@jonsequitur if you publish new packages, I'll fix up `PocketLogger` too.

**Comment by jonsequitur** [comment]
Done. I adjusted the package versions including dependencies but might have missed a few. New versions of all are uploaded.

**Pull request merged**
